name: Elixir Cache
description: Elixir Cache
runs:
  using: "composite"
  steps:
    - uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
      with:
        path: '**/deps'
        key: cache-elixir-${{ github.workflow }}-${{ github.job }}-ghcr.io/ockam-network/ockam/builder@sha256:41df07cc61029f7293430acde1fccc8d7162cd3130aa32d151e440c9f9b31626-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          cache-elixir-${{ github.workflow }}-${{ github.job }}-ghcr.io/ockam-network/ockam/builder@sha256:41df07cc61029f7293430acde1fccc8d7162cd3130aa32d151e440c9f9b31626-
