name: Gradle Cache
description: Gradle Home Cache
runs:
  using: "composite"
  steps:
    - uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
      with:
        path: /root/.gradle/wrapper/dists
        key: cache-gradle-${{ github.workflow }}-${{ github.job }}-ghcr.io/ockam-network/ockam/builder@sha256:41df07cc61029f7293430acde1fccc8d7162cd3130aa32d151e440c9f9b31626
        restore-keys: |
          cache-gradle-${{ github.workflow }}-${{ github.job }}-ghcr.io/ockam-network/ockam/builder@sha256:41df07cc61029f7293430acde1fccc8d7162cd3130aa32d151e440c9f9b31626
          cache-gradle-${{ github.workflow }}-${{ github.job }}-
          cache-gradle-${{ github.workflow }}-
          cache-gradle-
