name: CARGO_TARGET_DIR Cache
description: CARGO_TARGET_DIR Cache
runs:
  using: "composite"
  steps:
    - uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
      with:
        path: target
        key: cache-cargo-target----${{ github.workflow }}-${{ github.job }}-ghcr.io/ockam-network/ockam/builder@sha256:41df07cc61029f7293430acde1fccc8d7162cd3130aa32d151e440c9f9b31626-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: cache-cargo-target-${{ github.workflow }}-${{ github.job }}-ghcr.io/ockam-network/ockam/builder@sha256:41df07cc61029f7293430acde1fccc8d7162cd3130aa32d151e440c9f9b31626-

# https://doc.rust-lang.org/cargo/guide/build-cache.html
